const KEY='hanyu-campus-v2';
const demo={students:[{id:'anna',name:'Anna Petrova',initial:'A',language:'俄语',attendance:null},{id:'leo',name:'Leo Martin',initial:'L',language:'法语',attendance:null},{id:'maria',name:'Maria Santos',initial:'M',language:'西班牙语',attendance:null}],assignments:[{id:1,title:'我的中文名',type:'选择题 + 填空',due:'2026-09-18',status:'已发布',questions:3},{id:2,title:'数字 1–20',type:'选择题',due:'2026-09-21',status:'草稿',questions:8}],materials:[{id:1,name:'HSK 1 · 第三课：你叫什么名字？',type:'课本单元',updated:'今天'},{id:2,name:'课堂词汇音频与练习说明',type:'教师资料',updated:'昨天'}],attendance:{active:false,code:'',expires:0,records:{}}};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||demo;
let session=JSON.parse(localStorage.getItem('hanyu-session')||'null');
let page='home';
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const setSession=x=>{session=x;localStorage.setItem('hanyu-session',JSON.stringify(x));render()};
const toast=t=>{const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2300)};
function login(){document.getElementById('app').innerHTML=`<main class="auth"><div class="auth-card"><div class="brand" style="padding:0 0 24px"><span class="brandmark">汉</span> Hanyu Campus</div><div class="eyebrow">In-person Chinese learning</div><h1 class="h1">Welcome back</h1><p class="sub">Sign in to see today’s class and learning tasks.</p><form onsubmit="event.preventDefault();doLogin()" class="stack" style="margin-top:24px"><label>Username<input id="login-user" class="field" placeholder="anna or teacher" required></label><label>Password<input id="login-pass" type="password" class="field" placeholder="hanyu123" required></label><button class="btn">Sign in</button></form><p class="tip" style="margin-top:20px">Demo: <b>anna</b> or <b>teacher</b> · password <b>hanyu123</b></p></div></main>`}
function doLogin(){const u=document.getElementById('login-user').value.trim().toLowerCase();if(u==='anna'||u==='teacher'){setSession({role:u==='anna'?'student':'teacher',id:u})}else toast('请输入 anna 或 teacher')}
function avatar(s='A'){return `<span class="avatar">${s}</span>`}
function nav(){const student=[['home','Home'],['textbook','Textbook'],['homework','Homework'],['practice','Practice'],['grades','Grades / Profile']];const teacher=[['home','今日课程'],['students','学生管理'],['homework','作业管理'],['materials','教材/资料'],['activity','课堂活动'],['grades','成绩统计'],['settings','系统设置']];const items=session.role==='student'?student:teacher;return `<aside class="rail"><div class="brand"><span class="brandmark">汉</span> Hanyu Campus</div><nav class="nav">${items.map(([p,n])=>`<button class="${page===p?'active':''}" onclick="go('${p}')">${n}</button>`).join('')}</nav><div class="user-mini">${avatar(session.role==='student'?'A':'教')}<span><b>${session.role==='student'?'Anna Petrova':'林老师'}</b><br><small>${session.role==='student'?'HSK 1–2':'教师端'}</small></span></div></aside>`}
function top(title,kicker,sub='',action=''){return `<div class="topbar"><div><div class="eyebrow">${kicker}</div><h1 class="h1">${title}</h1>${sub?`<p class="sub">${sub}</p>`:''}</div>${action}</div>`}
function studentView(){if(page==='textbook')return textbook();if(page==='homework')return homeworkStudent();if(page==='practice')return practice();if(page==='grades')return gradesStudent();return studentHome()}
function studentHome(){const att=session.id==='anna'?db.students.find(x=>x.id==='anna')?.attendance:null;return `${top('Good afternoon, Anna.','Wednesday · 16 September 2026','Your next in-person class is ready.','<button class="btn secondary" onclick="go(\'grades\')">A　My profile</button>')}<div class="grid two"><section class="card hero"><span class="pill">Today’s Class · 第 6 次课</span><div class="class-time">14:00 — 17:20</div><div class="meta">Room B-204 · Chinese Foundations</div><p style="margin-top:28px">签到开放后，用手机扫描教室投影上的动态二维码。</p><button class="btn" style="background:#fff;color:var(--red)" onclick="toast('请在教师端开始签到后扫描二维码')">Scan to check in　→</button></section><section class="card"><div class="row"><h3>Attendance</h3><span class="status">${att===null?'暂无记录':att==='present'?'● Present':'待确认'}</span></div><div class="metric">${att===null?'—':att==='present'?'100%':'—'}</div><div class="bar"><i style="width:${att===null?0:100}%"></i></div><p class="meta">完成签到后，这里会显示你的实际出勤率。</p><hr style="border:0;border-top:1px solid var(--line)"><h3>Today’s focus</h3><p>Introducing yourself · names · countries</p></section></div><div class="grid three" style="margin-top:18px"><section class="card"><span class="pill">Homework</span><h3 style="margin-top:15px">我的中文名</h3><p class="meta">Due Friday · 3 exercises</p><button class="btn ghost" onclick="go('homework')">Continue →</button></section><section class="card"><span class="pill">Practice</span><h3 style="margin-top:15px">Numbers 1–20</h3><p class="meta">8 min recommended</p><button class="btn ghost" onclick="go('practice')">Start practice →</button></section><section class="card"><span class="pill">Progress</span><h3 style="margin-top:15px">Course average</h3><div class="metric">—<span style="font-size:16px"> / 100</span></div><p class="meta">还没有足够数据</p></section></div>`}
function textbook(){return `${top('你叫什么名字？','Textbook · 第三课','Vocabulary, dialogue and grammar for today.')}<div class="grid two"><section class="card"><div class="tabs"><button class="tab active">词汇</button><button class="tab">课文</button><button class="tab">语法</button></div><div class="list">${[['叫','jiào','to be called'],['什么','shénme','what'],['名字','míngzi','name'],['认识','rènshi','to know / meet']].map(x=>`<div class="list-item row"><span><b>${x[0]}</b> <span class="meta">${x[1]}</span></span><span class="meta">${x[2]}　◉</span></div>`).join('')}</div></section><section class="card"><h3>本课练习</h3><p class="tip">Listen, repeat, then practise the dialogue with a partner in class.</p><button class="btn" onclick="toast('音频播放中 · 你好！')">▶ 播放课文音频</button></section></div>`}
function homeworkStudent(){const a=db.assignments.filter(x=>x.status==='已发布');return `${top('Homework','Homework','Auto-graded exercises from your teacher.')}<div class="grid two"><section class="card"><div class="list">${a.map(x=>`<div class="list-item row"><span><b>${x.title}</b><br><span class="meta">${x.type} · ${x.questions} 题 · Due ${x.due}</span></span><button class="btn secondary" onclick="toast('作业已打开')">开始</button></div>`).join('')||'<p class="meta">暂无已发布作业</p>'}</div></section><section class="card"><h3>最近结果</h3><div class="metric">—</div><p class="meta">提交作业后会显示分数和错题。</p></section></div>`}
function practice(){return `${top('Choose a quick activity','Practice lab','Short activities for in-person practice.')}<div class="grid three">${[['Quiz','词汇小测','8 questions'],['Word Match','词语配对','Match 6 pairs'],['Sentence Order','句子排序','Build a sentence']].map(x=>`<section class="card"><span class="pill">${x[0]}</span><h3 style="margin-top:16px">${x[1]}</h3><p class="meta">${x[2]}</p><button class="btn" onclick="toast('${x[0]} 活动开始')">Start →</button></section>`).join('')}</div>`}
function gradesStudent(){return `${top('Your progress','Grades / Profile','成绩会根据出勤、作业和课堂活动逐步汇总。')}<div class="grid two"><section class="card"><h3>Course average</h3><div class="metric">— / 100</div><div class="bar"><i style="width:0"></i></div><div class="list"><div class="list-item row"><span>Attendance</span><b>—</b></div><div class="list-item row"><span>Homework</span><b>—</b></div><div class="list-item row"><span>Class activities</span><b>—</b></div></div></section><section class="card"><h3>Your profile</h3><div class="row">${avatar('A')}<label class="btn secondary">Upload avatar<input type="file" hidden accept="image/*" onchange="uploadAvatar(event)"></label></div><p><b>Anna Petrova</b><br><span class="meta">anna · Russian speaker · HSK 1–2</span></p></section></div>`}
function teacherView(){if(page==='students')return studentsPage();if(page==='homework')return assignmentsPage();if(page==='materials')return materialsPage();if(page==='activity')return activityPage();if(page==='grades')return gradesPage();if(page==='settings')return settingsPage();return teacherHome()}
function teacherHome(){const active=db.attendance.active;return `${top('今日课程','教师工作台 · 2026年9月16日','中文基础 · HSK 1–2 混合班 · B-204',`<button class="btn" onclick="startAttendance()">${active?'签到进行中':'开始签到'}</button>`)}<div class="grid two"><section class="card hero"><span class="pill">第 6 次课 · 14:00—17:20</span><h2 style="font-size:28px;margin-top:20px">自我介绍与国籍</h2><p class="hero sub">课堂流程：签到 → 词汇导入 → 对话练习 → Quiz</p><button class="btn" style="background:#fff;color:var(--red)" onclick="go('activity')">打开课堂控制 →</button></section><section class="card"><div class="row"><h3>签到状态</h3><span class="status">${active?'● 开放中':'今日尚未开始'}</span></div>${active?`<div class="code">${db.attendance.code}</div><p class="meta" style="text-align:center">动态码每 15 秒刷新 · 剩余 ${Math.max(0,Math.ceil((db.attendance.expires-Date.now())/60000))} 分钟</p>`:'<p class="tip">点击“开始签到”，投影动态二维码，学生登录后扫码。</p>'}<div class="row" style="margin-top:15px"><span>已签到 <b>${Object.values(db.attendance.records).filter(x=>x==='present').length}</b> / ${db.students.length}</span><button class="btn secondary" onclick="manualAttendance()">手动调整</button></div></section></div><div class="grid three" style="margin-top:18px"><section class="card"><span class="pill">学生</span><div class="metric">${db.students.length}</div><p class="meta">当前班级人数</p></section><section class="card"><span class="pill">作业</span><div class="metric">${db.assignments.filter(x=>x.status==='已发布').length}</div><p class="meta">已发布作业</p></section><section class="card"><span class="pill">资料</span><div class="metric">${db.materials.length}</div><p class="meta">教材和课堂资料</p></section></div>`}
function studentsPage(){return `${top('学生名单','学生管理','HSK 1–2 · 线下中文基础',`<button class="btn" onclick="addStudent()">＋ 添加学生</button>`)}<section class="card"><table class="table"><thead><tr><th>学生</th><th>母语</th><th>出勤</th><th>操作</th></tr></thead><tbody>${db.students.map(s=>`<tr><td>${avatar(s.initial)} <b style="vertical-align:top;display:inline-block;margin:7px 0 0 7px">${s.name}<br><span class="meta">${s.id}</span></b></td><td>${s.language}</td><td>${s.attendance===null?'暂无记录':s.attendance==='present'?'正常出勤':'待确认'}</td><td><button class="btn ghost" onclick="editStudent('${s.id}')">编辑</button><button class="btn ghost" onclick="removeStudent('${s.id}')">删除</button></td></tr>`).join('')}</tbody></table></section>`}
function assignmentsPage(){return `${top('作业管理','作业管理','创建、编辑并发布自动评分作业。',`<button class="btn" onclick="newAssignment()">＋ 新建作业</button>`)}<section class="card"><div class="list">${db.assignments.map(a=>`<div class="list-item row"><span><b>${a.title}</b><br><span class="meta">${a.type} · ${a.questions} 题 · 截止 ${a.due}</span></span><span><span class="pill">${a.status}</span> <button class="btn ghost" onclick="editAssignment(${a.id})">编辑/发布</button></span></div>`).join('')}</div></section>`}
function materialsPage(){return `${top('教材与资料','教材/资料','上传课堂资料，管理学生可见内容。',`<label class="btn">＋ 上传资料<input type="file" hidden onchange="addMaterial(event)"></label>`)}<section class="card"><div class="list">${db.materials.map(m=>`<div class="list-item row"><span><b>${m.name}</b><br><span class="meta">${m.type} · 更新于 ${m.updated}</span></span><button class="btn ghost" onclick="removeMaterial(${m.id})">删除</button></div>`).join('')}</div><p class="tip" style="margin-top:18px">课本 PDF 仅作为教师备课参考；公开页面只展示自建课程索引、词汇和练习。</p></section>`}
function activityPage(){return `${top('课堂活动控制','课堂活动','发布活动后，学生端会看到入口并记录完成情况。')}<div class="grid three">${['Quiz · 自我介绍','Word Match · 国籍','Sentence Order · 句型'].map(x=>`<section class="card"><h3>${x}</h3><p class="meta">可作为课堂确认并自动计入成绩</p><button class="btn" onclick="toast('活动已发布到学生端')">发布活动</button></section>`).join('')}</div>`}
function gradesPage(){return `${top('班级成绩概览','成绩统计','当前权重：出勤 30% · 作业 30% · 测验/活动 40%',`<button class="btn secondary" onclick="toast('权重设置已保存')">配置权重</button>`)}<section class="card"><table class="table"><thead><tr><th>学生</th><th>出勤</th><th>作业</th><th>活动</th><th>总评</th></tr></thead><tbody>${db.students.map(s=>`<tr><td><b>${s.name}</b></td><td>${s.attendance===null?'—':100}</td><td>—</td><td>—</td><td><b>—</b></td></tr>`).join('')}</tbody></table></section>`}
function settingsPage(){return `${top('系统设置','系统设置','课堂、账号和数据设置')}<section class="card stack"><label>课程名称<input class="field" value="线下国际中文课堂"></label><label>签到刷新间隔<select class="field"><option>15 秒</option><option>10 秒</option></select></label><button class="btn" onclick="toast('设置已保存')">保存设置</button><button class="btn secondary" onclick="logout()">退出登录</button></section>`}
function render(){if(!session)return login();document.getElementById('app').innerHTML=`<div class="shell">${nav()}<main class="main">${session.role==='student'?studentView():teacherView()}<p class="meta" style="margin-top:35px">${session.role==='student'?'Hanyu Campus · In-person learning':'Hanyu Campus 教学管理平台'} <button class="btn ghost" style="float:right" onclick="logout()">退出</button></p></main></div>`}
function go(p){page=p;render()}
function logout(){session=null;localStorage.removeItem('hanyu-session');render()}
function uploadAvatar(e){if(e.target.files[0])toast('头像已更新（本机演示）')}
function addStudent(){const name=prompt('学生姓名');if(!name)return;const id='student-'+Date.now();db.students.push({id,name,initial:name[0].toUpperCase(),language:'未填写',attendance:null});save();render();toast('学生已添加')}
function editStudent(id){const s=db.students.find(x=>x.id===id);const name=prompt('修改学生姓名',s.name);if(name){s.name=name;save();render();toast('学生信息已更新')}}
function removeStudent(id){if(!confirm('确定删除这名学生吗？'))return;db.students=db.students.filter(x=>x.id!==id);save();render();toast('学生已删除')}
function newAssignment(){const title=prompt('作业标题');if(!title)return;db.assignments.unshift({id:Date.now(),title,type:'选择题 / 判断题 / 填空题',due:'2026-09-24',status:'草稿',questions:5});save();render();toast('作业已创建，可继续编辑题目')}
function editAssignment(id){const a=db.assignments.find(x=>x.id===id);a.status=a.status==='已发布'?'草稿':'已发布';save();render();toast(a.status==='已发布'?'作业已发布':'作业已保存为草稿')}
function addMaterial(e){const f=e.target.files[0];if(!f)return;db.materials.unshift({id:Date.now(),name:f.name,type:'上传资料',updated:'刚刚'});save();render();toast('资料已上传并保存')}
function removeMaterial(id){if(!confirm('确定删除这份资料吗？'))return;db.materials=db.materials.filter(x=>x.id!==id);save();render();toast('资料已删除')}
function startAttendance(){db.attendance={active:true,code:Math.random().toString(36).slice(2,8).toUpperCase(),expires:Date.now()+300000,records:{}};save();render();toast('动态签到已开始');setTimeout(()=>{if(db.attendance.active&&Date.now()>db.attendance.expires){db.attendance.active=false;save();render()}},300000)}
function manualAttendance(){const s=db.students[0];if(!s)return;s.attendance=s.attendance==='present'?null:'present';db.attendance.records[s.id]=s.attendance||'absent';save();render();toast('已更新 '+s.name+' 的签到状态')}
render();
